apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: projet2025
  labels:
    app: projet2025
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projet2025
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: projet2025
    spec:
      containers:
        - name: projet2025
          image: projet2025:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"