apiVersion: v1
kind: ConfigMap
metadata:
  name: auto-sync-script
  namespace: test
data:
  check-and-update.sh: |
    #!/bin/sh
    set -eu

    # Valeurs par défaut sur lesquelles on peut surcharger via env du CronJob
    NAMESPACE="${NAMESPACE:-test}"
    DEPLOYMENT="${DEPLOYMENT:-projet2025}"
    CONTAINER="${CONTAINER:-projet2025}"
    IMAGE_REPO="${IMAGE_REPO:-docker.io/haitamleb/projet2025}"
    FOLLOW_TAG="${FOLLOW_TAG:-main}"

    echo "🔧 Namespace=$NAMESPACE, Deploy=$DEPLOYMENT, Container=$CONTAINER, Repo=$IMAGE_REPO, Follow=$FOLLOW_TAG"

    CURRENT_IMAGE=$(kubectl -n "$NAMESPACE" get deploy "$DEPLOYMENT" -o jsonpath='{.spec.template.spec.containers[0].image}')
    echo "🔍 Image actuelle : $CURRENT_IMAGE"

    TARGET_IMAGE="$IMAGE_REPO:$FOLLOW_TAG"
    echo "🔎 Image cible : $TARGET_IMAGE"

    if [ "$CURRENT_IMAGE" != "$TARGET_IMAGE" ]; then
      echo "🚀 Nouvelle version détectée → mise à jour…"
      kubectl -n "$NAMESPACE" set image "deployment/$DEPLOYMENT" "$CONTAINER=$TARGET_IMAGE" --record
    else
      echo "✅ Image déjà à jour."
    fi

    echo "DONE"
