name: CI/CD Pipeline

on:
  push:
    branches: [main]
  workflow_dispatch: {}

env:
  IMAGE_SHA: docker.io/${{ secrets.DOCKER_USERNAME }}/projet2025:${{ github.sha }}
  IMAGE_MAIN: docker.io/${{ secrets.DOCKER_USERNAME }}/projet2025:main

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r app/requirements.txt

      - name: Run unit tests
        run: pytest -q tests/

      # --- Build & push Docker Hub (sha + main) ---
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image (sha + main)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_SHA }}
            ${{ env.IMAGE_MAIN }}
